begin;
select plan(20);
select has_table('public','social_accounts','social account metadata exists');
select has_table('public','social_account_credentials','credential vault table exists');
select has_table('public','article_writing_scores','writing score table exists');
select has_table('public','ai_writing_usage','AI usage guard exists');
select has_table('public','article_polls','poll table exists');
select has_table('public','article_poll_options','poll options exist');
select has_table('public','article_poll_votes','poll votes exist');
select has_function('public','configure_social_handoff',array['uuid','text','text','text'],'safe handoff connector exists');
select has_function('public','disconnect_social_account',array['uuid'],'disconnect RPC exists');
select has_function('public','publish_feed_post',array['uuid','text','jsonb','text[]','uuid[]','text[]','jsonb'],'composer publication RPC exists');
select has_function('public','create_article_poll',array['uuid','text','text[]','integer'],'poll creation RPC exists');
select has_function('public','vote_article_poll',array['uuid','uuid'],'poll voting RPC exists');
select has_function('public','reserve_ai_writing_generation',array['text'],'AI usage reservation RPC exists');
select table_privs_are('public','social_account_credentials','authenticated',array[]::text[],'frontend cannot read connector credentials');
select function_privs_are('public','publish_feed_post',array['uuid','text','jsonb','text[]','uuid[]','text[]','jsonb'],'authenticated',array['EXECUTE'],'authenticated composers can publish');
select function_privs_are('public','publish_feed_post',array['uuid','text','jsonb','text[]','uuid[]','text[]','jsonb'],'anon',array[]::text[],'anonymous publishing is blocked');
select col_is_pk('public','article_writing_scores','article_id','one current writing score per article');
select col_is_pk('public','article_polls','article_id','one poll per article');
select has_index('public','social_accounts','social_accounts_owner_idx','social accounts have owner index');
select has_index('public','article_poll_votes','article_poll_votes_option_idx','poll votes have option index');
select * from finish();
rollback;
