import { useEffect, useMemo, useState } from "react";
import {
  Activity, ArrowLeft, ArrowRight, BarChart3, BriefcaseBusiness, Check, Clock3, Edit3,
  FileText, Globe2, Loader2, LockKeyhole, Play, Plus, RefreshCw, Save, ShieldCheck,
  Sparkles, Upload, UserRound, Workflow as WorkflowIcon, X, Zap,
} from "lucide-react";
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, addEdge, useEdgesState, useNodesState } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { supabase } from "../../supabase.js";
import { loadTenantContext } from "../../tenant.js";
import { StackCraftService } from "../services/stackCraft.ts";
import { buildCountryOptions, flagForCountry } from "./countries.ts";
import "./stackcraft-workspace.css";

const service = new StackCraftService(supabase);
const COUNTRIES = buildCountryOptions();
const DEFAULT_ROLES=["Enterprise AI Solution Architect","GenAI Solution Architect","Agentic AI Architect","Principal AI Engineer","Staff AI Engineer"];
const STATUS_ORDER=["PREPARING","AWAITING_APPROVAL","APPROVED","SUBMITTED","VIEWED","RECRUITER_CONTACT","INTERVIEW","OFFER","REJECTED","WITHDRAWN","FAILED"];
const WORKFLOW_NODES=[
  {id:"discover",position:{x:20,y:120},data:{label:"Discover jobs",kind:"job_search"}},
  {id:"freshness",position:{x:240,y:120},data:{label:"Freshness gate",kind:"condition"}},
  {id:"match",position:{x:460,y:120},data:{label:"Match score",kind:"match"}},
  {id:"visa",position:{x:680,y:60},data:{label:"Visa / sponsor",kind:"visa_check"}},
  {id:"salary",position:{x:680,y:190},data:{label:"Salary gate",kind:"salary_check"}},
  {id:"approval",position:{x:920,y:120},data:{label:"Human approval",kind:"request_approval"}},
];
const WORKFLOW_EDGES=[
  {id:"e1",source:"discover",target:"freshness"},{id:"e2",source:"freshness",target:"match"},{id:"e3",source:"match",target:"visa"},{id:"e4",source:"match",target:"salary"},{id:"e5",source:"visa",target:"approval"},{id:"e6",source:"salary",target:"approval"},
];
function go(path){window.location.assign(path)}
function fmtDate(value){if(!value)return "—"; const d=new Date(value); return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(d)}
function ageLabel(value){if(!value)return "Unknown"; const days=Math.floor((Date.now()-new Date(value).getTime())/86400000); if(days<=0)return "Today"; if(days===1)return "1 day"; return `${days} days`;}
function statusTone(status){if(status==="OFFER")return "good";if(status==="INTERVIEW"||status==="RECRUITER_CONTACT")return "active";if(status==="REJECTED"||status==="FAILED")return "bad";if(status==="SUBMITTED"||status==="VIEWED")return "progress";return "neutral"}
function Node({data}){return <div className="sc-flow-node"><Handle type="target" position={Position.Left}/><span>{data.kind?.replaceAll("_"," ")}</span><strong>{data.label}</strong><Handle type="source" position={Position.Right}/></div>}
const nodeTypes={stackcraft:Node};

function Metric({label,value,note}){return <article className="sc-metric"><small>{label}</small><strong>{value}</strong><span>{note}</span></article>}
function Empty({title,copy}){return <div className="sc-empty"><Sparkles size={20}/><strong>{title}</strong><span>{copy}</span></div>}
function Field({label,value,blurred,editing,onEdit,onChange}){return <div className="sc-field"><div><small>{label}</small>{editing?<input value={value||""} onChange={e=>onChange(e.target.value)}/>:<strong className={blurred?"is-blurred":""}>{value||"Not found in CV"}</strong>}</div><button type="button" onClick={onEdit}><Edit3 size={14}/>{editing?"Done":"Edit"}</button></div>}

export default function StackCraftWorkspace(){
  const [state,setState]=useState("loading"),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [tenant,setTenant]=useState(null),[user,setUser]=useState(null),[data,setData]=useState(null),[tab,setTab]=useState("overview");
  const [identity,setIdentity]=useState({full_name:"",email:"",phone_e164:"",location_text:"",linkedin_url:"",professional_summary:""});
  const [editFields,setEditFields]=useState(new Set()),[uploading,setUploading]=useState(false),[countryQuery,setCountryQuery]=useState("");
  const [selectedCountries,setSelectedCountries]=useState([]),[roles,setRoles]=useState(DEFAULT_ROLES),[roleDraft,setRoleDraft]=useState("");
  const [workflowRunning,setWorkflowRunning]=useState(false),[workflowEvents,setWorkflowEvents]=useState([]);
  const [nodes,setNodes,onNodesChange]=useNodesState(WORKFLOW_NODES.map(n=>({...n,type:"stackcraft"}))); const [edges,setEdges,onEdgesChange]=useEdgesState(WORKFLOW_EDGES);

  const refresh=async(t=tenant,u=user)=>{if(!t?.id||!u?.id)return; const next=await service.loadWorkspace(t.id,u.id); setData(next); setIdentity({full_name:next.identity?.full_name||"",email:next.identity?.email||u.email||"",phone_e164:next.identity?.phone_e164||"",location_text:next.identity?.location_text||"",linkedin_url:next.identity?.linkedin_url||"",professional_summary:next.identity?.professional_summary||""}); setSelectedCountries(next.countries.map(c=>({...c}))); if(next.roles.length)setRoles(next.roles.map(r=>r.role_name)); if(next.workflows[0]?.definition?.nodes?.length){setNodes(next.workflows[0].definition.nodes.map(n=>({...n,type:"stackcraft"})));setEdges(next.workflows[0].definition.edges||[]);} };

  useEffect(()=>{let alive=true;(async()=>{try{const {data:auth}=await supabase.auth.getUser(); if(!auth.user){go("/login?next=%2FCraft%2Fapp&product=stackcraft");return;} const ctx=await loadTenantContext(auth.user.id); if(!ctx?.tenant)throw new Error("Your StackedIN tenant is not ready."); if(!alive)return;setUser(auth.user);setTenant(ctx.tenant);await service.ensureProfile(ctx.tenant.id,auth.user.id);await service.ensureTrial(ctx.tenant.id,auth.user.id);await refresh(ctx.tenant,auth.user);if(alive)setState("ready");}catch(e){if(alive){setError(e instanceof Error?e.message:"StackCraft could not start");setState("error")}}})();return()=>{alive=false}},[]);

  const apps=data?.applications||[],matches=data?.matches||[],runs=data?.runs||[],latestRun=runs[0],latestApp=apps[0],parsed=data?.identity?.extraction_status==="PARSED",reviewed=data?.identity?.extraction_status==="REVIEWED";
  const statusCounts=useMemo(()=>STATUS_ORDER.map(status=>({status,count:apps.filter(a=>a.status===status).length})).filter(x=>x.count),[apps]);
  const countryCounts=useMemo(()=>{const m=new Map();apps.forEach(a=>{const c=a.job?.country_code||"??";m.set(c,(m.get(c)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[apps]);
  const filteredCountries=COUNTRIES.filter(c=>`${c.name} ${c.code}`.toLowerCase().includes(countryQuery.toLowerCase())).slice(0,80);

  async function uploadCV(event){const file=event.target.files?.[0];event.target.value="";if(!file)return;setUploading(true);setError("");try{await service.uploadAndParseCV(tenant.id,user.id,file);setNotice("CV saved and parsed. Review the blurred extracted fields before confirming them.");await refresh();setTab("profile");}catch(e){setError(e instanceof Error?e.message:"CV upload failed")}finally{setUploading(false)}}
  async function saveIdentity(){try{await service.saveIdentity(tenant.id,user.id,identity);setEditFields(new Set());setNotice("CV identity reviewed and saved to this StackedIN profile only.");await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save profile")}}
  async function saveTargets(){try{await service.replaceCountries(tenant.id,user.id,selectedCountries.map(c=>({country_code:c.country_code,priority:Number(c.priority||50),minimum_salary:c.minimum_salary?Number(c.minimum_salary):null,currency:c.currency||null,visa_required:c.visa_required!==false,relocation_required:c.relocation_required!==false,enabled:true})));await service.replaceRoles(tenant.id,user.id,roles);setNotice("Target markets and roles saved.");await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save targets")}}
  function toggleCountry(option){setSelectedCountries(current=>{const found=current.some(c=>c.country_code===option.code);if(found)return current.filter(c=>c.country_code!==option.code);if(current.length>=15){setError("You can target up to 15 countries at a time.");return current;}return [...current,{country_code:option.code,priority:50,minimum_salary:"",currency:option.currency,visa_required:true,relocation_required:true,enabled:true}]})}
  async function saveWorkflow(){try{const wf=await service.saveWorkflow(tenant.id,user.id,"Global opportunity radar",nodes.map(({id,position,data,type})=>({id,position,data,type})),edges);setNotice(`Workflow v${wf.version} saved.`);await refresh();return wf}catch(e){setError(e instanceof Error?e.message:"Workflow save failed");return null}}
  async function runWorkflow(){setWorkflowRunning(true);setWorkflowEvents([]);setError("");try{const wf=await saveWorkflow();if(!wf)return;const result=await service.runWorkflow(tenant.id,wf.id);setNotice(`Workflow scanned ${result.jobsScanned} jobs and shortlisted ${result.shortlisted}.`);setWorkflowEvents(await service.workflowEvents(result.runId));await refresh();}catch(e){setError(e instanceof Error?e.message:"Workflow run failed")}finally{setWorkflowRunning(false)}}

  if(state==="loading")return <main className="sc-state"><Loader2 className="sc-spin"/><strong>Opening StackCraft…</strong><span>Reusing your secure StackedIN session.</span></main>;
  if(state==="error")return <main className="sc-state"><ShieldCheck/><strong>StackCraft needs attention</strong><span>{error}</span><button onClick={()=>location.reload()}>Retry</button></main>;

  return <main className="sc-app">
    <aside className="sc-sidebar">
      <button className="sc-brand" onClick={()=>go("/Craft")}><img src="/stackcraft-mark.svg" alt=""/><div><strong>StackCraft</strong><small>by StackedIN</small></div></button>
      <nav>{[["overview",Activity,"Overview"],["profile",UserRound,"Career Profile"],["targets",Globe2,"Countries & Roles"],["applications",BriefcaseBusiness,"Applications"],["workflows",WorkflowIcon,"Workflows"],["sources",RefreshCw,"Sources"]].map(([id,Icon,label])=><button key={id} className={tab===id?"is-active":""} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</nav>
      <div className="sc-side-bottom"><span><LockKeyhole size={13}/> Private tenant</span><button onClick={()=>go("/")}><ArrowLeft size={15}/> StackedIN</button></div>
    </aside>
    <section className="sc-main">
      <header className="sc-topbar"><div><small>Career operating system</small><strong>{data?.identity?.full_name||user?.email||"StackCraft"}</strong></div><div className="sc-top-actions"><span>{data?.subscription?.plan==="TRIAL"?"24-hour audit":"Premium"}</span><button onClick={()=>refresh()}><RefreshCw size={14}/> Refresh</button></div></header>
      {error?<div className="sc-alert bad">{error}<button onClick={()=>setError("")}><X size={14}/></button></div>:null}{notice?<div className="sc-alert good"><Check size={14}/>{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>:null}

      {tab==="overview"?<div className="sc-page">
        <div className="sc-heading"><div><span>Command center</span><h1>Career execution at a glance.</h1><p>Applications, market coverage, workflow health and job freshness from your private StackCraft tenant.</p></div><button className="sc-primary" onClick={()=>setTab("workflows")}><Play size={15}/> Run opportunity radar</button></div>
        <section className="sc-metrics"><Metric label="Applications" value={apps.length} note={`${apps.filter(a=>a.status==="INTERVIEW").length} interviews`}/><Metric label="High matches" value={matches.filter(m=>Number(m.overall_score)>=90).length} note="90%+ score"/><Metric label="Target countries" value={selectedCountries.length} note="up to 15"/><Metric label="Last workflow" value={latestRun?.status||"Not run"} note={fmtDate(latestRun?.created_at)}/></section>
        <div className="sc-grid two">
          <section className="sc-card"><div className="sc-card-title"><div><BarChart3 size={16}/><strong>Application funnel</strong></div><span>Live from Supabase</span></div>{statusCounts.length?<div className="sc-bars">{statusCounts.map(x=><div key={x.status}><span>{x.status.replaceAll("_"," ")}</span><div><i style={{width:`${Math.max(8,x.count/Math.max(...statusCounts.map(v=>v.count))*100)}%`}}/></div><b>{x.count}</b></div>)}</div>:<Empty title="No applications yet" copy="Runs and imports will populate the funnel."/>}</section>
          <section className="sc-card"><div className="sc-card-title"><div><Globe2 size={16}/><strong>Applications by country</strong></div><span>Top markets</span></div>{countryCounts.length?<div className="sc-country-chart">{countryCounts.map(([code,count])=><div key={code}><span>{code==="??"?"🌐":flagForCountry(code)} {code}</span><strong>{count}</strong></div>)}</div>:<Empty title="No country activity" copy="Select target markets and run discovery."/>}</section>
        </div>
        <section className="sc-card"><div className="sc-card-title"><div><BriefcaseBusiness size={16}/><strong>Recent applications</strong></div><button onClick={()=>setTab("applications")}>View all <ArrowRight size={14}/></button></div>{apps.length?<div className="sc-table-wrap"><table className="sc-table"><thead><tr><th>Company</th><th>Role</th><th>Country</th><th>Match</th><th>Freshness</th><th>Status</th><th>Last activity</th></tr></thead><tbody>{apps.slice(0,8).map(a=><tr key={a.id}><td><strong>{a.job?.company_name||"—"}</strong><small>{a.job?.source||"manual"}</small></td><td>{a.job?.role_title||"—"}</td><td>{a.job?.country_code?`${flagForCountry(a.job.country_code)} ${a.job.country_code}`:"—"}</td><td>{a.match?.overall_score?`${a.match.overall_score}%`:"—"}</td><td>{ageLabel(a.job?.published_at||a.job?.discovered_at)}</td><td><span className={`sc-status ${statusTone(a.status)}`}>{a.status.replaceAll("_"," ")}</span></td><td>{fmtDate(a.last_status_at)}</td></tr>)}</tbody></table></div>:<Empty title="Nothing applied yet" copy="Your latest applied job, country and status will appear here."/>}</section>
        {latestApp?<section className="sc-last-run"><span>Last application</span><strong>{latestApp.job?.role_title} · {latestApp.job?.company_name}</strong><small>{latestApp.job?.country_code?flagForCountry(latestApp.job.country_code):"🌐"} {latestApp.status} · {fmtDate(latestApp.last_status_at)}</small></section>:null}
      </div>:null}

      {tab==="profile"?<div className="sc-page"><div className="sc-heading"><div><span>Candidate evidence</span><h1>Upload once. Review what StackCraft extracts.</h1><p>Your CV is stored in your private document vault. Parsed values remain visually blurred until you review them.</p></div><label className="sc-primary file">{uploading?<Loader2 className="sc-spin" size={15}/>:<Upload size={15}/>} {uploading?"Parsing CV…":"Upload CV"}<input type="file" accept=".pdf,.docx,.txt" onChange={uploadCV}/></label></div>
        <section className="sc-card sc-profile-card"><div className="sc-card-title"><div><FileText size={16}/><strong>CV identity</strong></div><span>{data?.identity?.extraction_status||"Not parsed"}</span></div><div className="sc-fields">{[["Full name","full_name"],["Email","email"],["Mobile","phone_e164"],["Location","location_text"],["LinkedIn","linkedin_url"]].map(([label,key])=><Field key={key} label={label} value={identity[key]} blurred={parsed&&!reviewed&&!editFields.has(key)} editing={editFields.has(key)} onEdit={()=>setEditFields(current=>{const n=new Set(current);n.has(key)?n.delete(key):n.add(key);return n})} onChange={v=>setIdentity(x=>({...x,[key]:v}))}/>)}</div><div className="sc-summary"><small>Professional summary</small><textarea className={parsed&&!reviewed&&!editFields.has("professional_summary")?"is-blurred":""} value={identity.professional_summary||""} onFocus={()=>setEditFields(c=>new Set(c).add("professional_summary"))} onChange={e=>setIdentity(x=>({...x,professional_summary:e.target.value}))}/></div><button className="sc-primary" onClick={saveIdentity}><Save size={15}/> Confirm & save profile</button></section>
        <div className="sc-grid two"><section className="sc-card"><div className="sc-card-title"><strong>Work history timeline</strong><span>{data?.experiences?.length||0} roles</span></div>{data?.experiences?.length?<div className="sc-timeline">{data.experiences.map(x=><article key={x.id}><i/><div><strong>{x.role_title||"Role"}</strong><span>{x.company_name}</span><small>{x.started_on||"?"} → {x.is_current?"Present":x.ended_on||"?"}</small>{x.technologies?.length?<p>{x.technologies.slice(0,8).join(" · ")}</p>:null}</div><em>{Math.round(Number(x.confidence||0)*100)}%</em></article>)}</div>:<Empty title="No work history parsed" copy="Upload a text-based CV to build your timeline."/>}</section><section className="sc-card"><div className="sc-card-title"><strong>Tech stack</strong><span>{data?.skills?.length||0} skills</span></div>{data?.skills?.length?<div className="sc-chips">{data.skills.map(s=><span key={s.id} className={s.verified?"verified":""}>{s.skill_name}{s.verified?<Check size={11}/>:null}</span>)}</div>:<Empty title="No tech stack yet" copy="Skills extracted from the CV appear here for review."/>}</section></div>
      </div>:null}

      {tab==="targets"?<div className="sc-page"><div className="sc-heading"><div><span>Global mobility</span><h1>Choose up to 15 countries.</h1><p>Flags, salary floors, sponsorship policy and role targets are stored per StackCraft profile.</p></div><button className="sc-primary" onClick={saveTargets}><Save size={15}/> Save targets</button></div><section className="sc-card"><div className="sc-country-search"><input placeholder="Search all countries…" value={countryQuery} onChange={e=>setCountryQuery(e.target.value)}/><span>{selectedCountries.length}/15 selected</span></div><div className="sc-country-picker">{filteredCountries.map(c=>{const chosen=selectedCountries.some(x=>x.country_code===c.code);return <button key={c.code} className={chosen?"selected":""} onClick={()=>toggleCountry(c)}><span>{c.flag}</span><div><strong>{c.name}</strong><small>{c.code}{c.currency?` · ${c.currency}`:""}</small></div>{chosen?<Check size={15}/>:<Plus size={15}/>}</button>})}</div></section><section className="sc-card"><div className="sc-card-title"><strong>Selected markets</strong><span>salary + visa controls</span></div><div className="sc-market-list">{selectedCountries.map(c=>{const o=COUNTRIES.find(x=>x.code===c.country_code);return <article key={c.country_code}><div><span>{o?.flag||flagForCountry(c.country_code)}</span><strong>{o?.name||c.country_code}</strong></div><label>Min salary<input type="number" value={c.minimum_salary||""} onChange={e=>setSelectedCountries(v=>v.map(x=>x.country_code===c.country_code?{...x,minimum_salary:e.target.value}:x))}/></label><label>Currency<input value={c.currency||""} maxLength={3} onChange={e=>setSelectedCountries(v=>v.map(x=>x.country_code===c.country_code?{...x,currency:e.target.value.toUpperCase()}:x))}/></label><label className="check"><input type="checkbox" checked={c.visa_required!==false} onChange={e=>setSelectedCountries(v=>v.map(x=>x.country_code===c.country_code?{...x,visa_required:e.target.checked}:x))}/> Visa/sponsorship required</label></article>})}</div></section><section className="sc-card"><div className="sc-card-title"><strong>Target roles</strong><span>{roles.length}/20</span></div><div className="sc-role-add"><input value={roleDraft} onChange={e=>setRoleDraft(e.target.value)} placeholder="Add a role" onKeyDown={e=>{if(e.key==="Enter"&&roleDraft.trim()){setRoles(v=>[...new Set([...v,roleDraft.trim()])].slice(0,20));setRoleDraft("")}}}/><button onClick={()=>{if(roleDraft.trim()){setRoles(v=>[...new Set([...v,roleDraft.trim()])].slice(0,20));setRoleDraft("")}}}><Plus size={14}/> Add</button></div><div className="sc-chips">{roles.map(r=><span key={r}>{r}<button onClick={()=>setRoles(v=>v.filter(x=>x!==r))}><X size={11}/></button></span>)}</div></section></div>:null}

      {tab==="applications"?<div className="sc-page"><div className="sc-heading"><div><span>Application ledger</span><h1>Every application. Every state change.</h1><p>Country, source, match score, freshness and status are kept in an immutable timeline.</p></div></div><section className="sc-card">{apps.length?<div className="sc-table-wrap"><table className="sc-table"><thead><tr><th>Company</th><th>Role</th><th>Country</th><th>Source</th><th>Match</th><th>Freshness</th><th>Status</th><th>Updated</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td><strong>{a.job?.company_name||"—"}</strong></td><td>{a.job?.role_title||"—"}</td><td>{a.job?.country_code?`${flagForCountry(a.job.country_code)} ${a.job.country_code}`:"—"}</td><td>{a.job?.source||"—"}</td><td>{a.match?.overall_score?`${a.match.overall_score}%`:"—"}</td><td>{ageLabel(a.job?.published_at||a.job?.discovered_at)}</td><td><span className={`sc-status ${statusTone(a.status)}`}>{a.status.replaceAll("_"," ")}</span></td><td>{fmtDate(a.last_status_at)}</td></tr>)}</tbody></table></div>:<Empty title="No application history" copy="The ledger will fill as StackCraft prepares and submits authorized applications."/>}</section></div>:null}

      {tab==="workflows"?<div className="sc-page"><div className="sc-heading"><div><span>Workflow OS</span><h1>Drag, connect, save, run.</h1><p>React Flow powers the visual policy. Supabase Edge Functions execute the current normalized-job pipeline.</p></div><div className="sc-run-actions"><button onClick={saveWorkflow}><Save size={15}/> Save</button><button className="sc-primary" onClick={runWorkflow} disabled={workflowRunning}>{workflowRunning?<Loader2 className="sc-spin" size={15}/>:<Play size={15}/>} Run</button></div></div><section className="sc-flow-wrap"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={c=>setEdges(es=>addEdge(c,es))} nodeTypes={nodeTypes} fitView><Background gap={18}/><MiniMap pannable zoomable/><Controls/></ReactFlow></section><section className="sc-card"><div className="sc-card-title"><div><Zap size={16}/><strong>Run events</strong></div><span>{latestRun?.status||"Not run"}</span></div>{workflowEvents.length?<div className="sc-events">{workflowEvents.map(e=><article key={e.id}><span className={`sc-event-dot ${e.status.toLowerCase()}`}/><div><strong>{e.node_type?.replaceAll("_"," ")}</strong><p>{e.message}</p></div><small>{e.status}</small></article>)}</div>:latestRun?<div className="sc-last-run"><span>Last run</span><strong>{latestRun.status}</strong><small>{fmtDate(latestRun.created_at)} · {latestRun.summary?.jobs_scanned||0} scanned · {latestRun.summary?.shortlisted||0} shortlisted</small></div>:<Empty title="Workflow has not run" copy="Save the graph and run the opportunity radar."/>}</section></div>:null}

      {tab==="sources"?<div className="sc-page"><div className="sc-heading"><div><span>Authorized sources</span><h1>Fresh jobs without credential scraping.</h1><p>StackCraft will ingest authorized exports, ATS feeds and company career pages into one normalized job index.</p></div></div><div className="sc-grid two"><section className="sc-card source"><strong>LinkedIn</strong><p>Profile/job ingestion must use authorized export or approved partner access. StackCraft will not automate personal credentials or bypass platform controls.</p><span>Partner / export connector</span></section><section className="sc-card source"><strong>Naukri</strong><p>Use recruiter/export integrations or user-provided exports where permitted. No browser credential automation.</p><span>Authorized import connector</span></section><section className="sc-card source"><strong>Company ATS</strong><p>Greenhouse, Lever, Ashby and public company career feeds are the preferred discovery path for freshness and application reliability.</p><span>Next connector slice</span></section><section className="sc-card source"><strong>Freshness policy</strong><p>Each normalized job carries published/discovered timestamps. The current workflow scores today/3d/7d/14d/30d freshness without inventing dates.</p><span>Active in workflow v1</span></section></div></div>:null}
    </section>
  </main>
}
