import { useState } from "react";
import { CheckCircle2, Eye, EyeOff, KeyRound, LoaderCircle, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import { SiAnthropic } from "@icons-pack/react-simple-icons";
import { activateAIProvider, forgetAIProvider, getAIProviderConfiguration, selectAIProviderModel } from "../services/aiProviderSession.js";
import { supabase } from "../../supabase.js";

export const AI_PROVIDERS = {
  sarvam: { label: "Sarvam", model: "sarvam-105b", included: true },
  openai: { label: "OpenAI", included: false },
  anthropic: { label: "Anthropic", included: false },
};

export function AIProviderIcon({ provider, size = 18 }) {
  if (provider === "openai") return <span aria-hidden="true" className="openai-provider-mark" style={{ width: size, height: size }}>AI</span>;
  if (provider === "anthropic") return <SiAnthropic aria-hidden="true" size={size} />;
  return <span aria-hidden="true" className="sarvam-provider-mark" style={{ width: size, height: size }}>S</span>;
}

export function AIResponseAttribution({ response }) {
  if (!response) return null;
  return <div className={`ai-response-attribution ${response.provider}`} title={`Generated by ${AI_PROVIDERS[response.provider]?.label || response.provider} using ${response.model}`}>
    <AIProviderIcon provider={response.provider} size={15} />
    <span><small>Drafted with</small><strong>{AI_PROVIDERS[response.provider]?.label || response.provider} · {response.model}</strong></span>
  </div>;
}

export default function AIProviderControls({ provider, model, onProviderChange, onModelChange }) {
  const [apiKey, setApiKey] = useState("");
  const [showKey, setShowKey] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [, setRevision] = useState(0);
  const configuration = provider === "sarvam" ? null : getAIProviderConfiguration(provider);
  const models = configuration?.models || [];

  const chooseProvider = event => {
    const nextProvider = event.target.value;
    const configured = getAIProviderConfiguration(nextProvider);
    onProviderChange(nextProvider);
    onModelChange(nextProvider === "sarvam" ? AI_PROVIDERS.sarvam.model : configured?.model || "");
    setApiKey("");
    setMessage("");
  };
  const testAndActivate = async () => {
    if (!apiKey.trim()) return setMessage(`Enter your ${AI_PROVIDERS[provider].label} API key first.`);
    setBusy(true); setMessage("");
    try {
      const { data } = await supabase.auth.getSession();
      const response = await fetch("/api/ai-models", {
        method: "POST",
        headers: { "content-type": "application/json", authorization: `Bearer ${data.session?.access_token || ""}` },
        body: JSON.stringify({ provider, apiKey: apiKey.trim() }),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload.error || "The provider rejected this key.");
      const availableModels = Array.isArray(payload.models) ? payload.models : [];
      if (!availableModels.length) throw new Error("The key is valid, but no supported writing models were returned.");
      const selectedModel = availableModels[0].id;
      activateAIProvider(provider, { apiKey: apiKey.trim(), model: selectedModel, models: availableModels });
      onModelChange(selectedModel);
      setApiKey("");
      setMessage(`${AI_PROVIDERS[provider].label} is active for this browser session.`);
      setRevision(value => value + 1);
    } catch (error) { setMessage(error.message || "The provider connection could not be tested."); }
    finally { setBusy(false); }
  };
  const chooseModel = event => {
    const nextModel = event.target.value;
    selectAIProviderModel(provider, nextModel);
    onModelChange(nextModel);
    setRevision(value => value + 1);
  };
  const forget = () => {
    forgetAIProvider(provider);
    onModelChange("");
    setMessage(`${AI_PROVIDERS[provider].label} key removed from this session.`);
    setRevision(value => value + 1);
  };

  return <div className="ai-provider-controls">
    <div className="ai-provider-picker">
      <label><span>Provider</span><div><AIProviderIcon provider={provider} size={16} /><select value={provider} onChange={chooseProvider}><option value="sarvam">Sarvam · Default</option><option value="openai">OpenAI · Bring your key</option><option value="anthropic">Anthropic · Bring your key</option></select></div></label>
      <label><span>Model</span><select value={model} disabled={provider !== "sarvam" && !configuration} onChange={chooseModel}>{provider === "sarvam" ? <option value="sarvam-105b">sarvam-105b</option> : models.length ? models.map(item => <option key={item.id} value={item.id}>{item.name || item.id}</option>) : <option value="">Test a key to load models</option>}</select></label>
    </div>
    {provider === "sarvam" ? <div className="ai-provider-ready included"><CheckCircle2 size={14} /><span><strong>Included by StackedIN</strong><small>The platform Sarvam key is used securely on the server.</small></span></div> : configuration ? <div className="ai-provider-ready"><ShieldCheck size={14} /><span><strong>{AI_PROVIDERS[provider].label} routing active</strong><small>Verified for this session · key is kept in memory only</small></span><button type="button" onClick={forget}><Trash2 size={12} />Forget key</button></div> : <div className="ai-provider-key"><label><KeyRound size={14} /><input type={showKey ? "text" : "password"} value={apiKey} onChange={event => setApiKey(event.target.value)} autoComplete="off" spellCheck="false" placeholder={`Paste ${AI_PROVIDERS[provider].label} API key`} /><button type="button" title={showKey ? "Hide key" : "Show key"} onClick={() => setShowKey(value => !value)}>{showKey ? <EyeOff size={14} /> : <Eye size={14} />}</button></label><button type="button" disabled={busy || !apiKey.trim()} onClick={testAndActivate}>{busy ? <LoaderCircle className="spin" size={13} /> : <RefreshCw size={13} />}Test & activate</button></div>}
    {message && <p className="ai-provider-message">{message}</p>}
  </div>;
}
